### ISSUE TITLE
Stats row `<tr class="stats-th">` still visible even when there's no summary for the QueryResult

### ISSUE THREAD

**Issue by ernstki** [chrisclark/django-sql-explorer#573] opened 2024-01-20 00:44 UTC
Hi all, hope you're doing well. I plan on doing a PR for this.

In the latest release (3.2.1) the `<tr class="stats-th">` in [`explorer/templates/explorer/preview_pane.html`](../blob/3.2.1/explorer/templates/explorer/preview_pane.html#L92) is displayed even when there are no recognized numeric columns, _i.e._, [`explorer.models.QueryResult.process_columns`](../blob/2e543f3de610fcf2088dbcbc2aa6cc4e98efb40d/explorer/models.py#L298) doesn't add a `.summary`. This isn't a tragedy, obviously, but I think it's probably still a bug.

![Screenshot of the preview pane highlighting the extra table row with the browser dev tools](https://github.com/chrisclark/django-sql-explorer/assets/4009681/cde67f4e-f337-448c-a066-39613f90b83c)

I should be able to fix that by just relocating [the conditional](https://github.com/chrisclark/django-sql-explorer/blob/3.2.1/explorer/templates/explorer/preview_pane.html#L96) in the template, no problem.

In the same PR, I also intend to remove this chunk of extra space within each `<td>`, by just trimming some whitespace in the template. I know that gobs of extra whitespace is _en vogue_ these days, but I think this was just an accident. `;)`

![Screenshot of the preview pane highlighting the extra whitespace in each table data cell](https://github.com/chrisclark/django-sql-explorer/assets/4009681/dfbd9966-e4dd-4cf8-8bdb-4a7a46197b0d)

The question I have, though, is how do I do a PR for the 3.x series? The `master` branch seems to be moving fast toward a new release with breaking changes, and I [ran into some problems](https://github.com/chrisclark/django-sql-explorer/commit/95b1a842ab2bec856284ef8c0f637a3ee0935239#r137470270) trying to patch `master`, which I don't think I'm qualified to resolve (JavaScript stuff).

Can I just do a PR against `3.2.1`, or should I just cool out for a while until `master` is more stabilized?

**Comment by marksweb** [comment] 2024-01-20 00:52
Hi @ernstki, you're right. The frontend has had a revamp so I think `master` is headed for v4

I think what we'll need to do is create a branch for 3.x support. I may be able to set this up soon. Otherwise I'll sort tomorrow (I'm on UK time, approaching 1am)

**Comment by ernstki** [comment] 2024-01-20 00:57
@marksweb OK, super, thanks. That's a relief.

No rush. We can just override the template in our own application with the fixes in the meantime, and it's just a visual appearance thing anyway.

**Comment by marksweb** [comment] 2024-01-20 01:24
Ok I've setup a `support/3.x` branch;

https://github.com/chrisclark/django-sql-explorer/tree/support/3.x

Start a branch from there and we can release safely.

**Comment by chrisclark** [comment] 2024-01-31 14:23
@ernstki this has been addressed here:
https://github.com/chrisclark/django-sql-explorer/pull/577/commits/b6fec1019b68c3c5df4a2504661cc5d6ff1b34f4

And will be included in the 4.0 release coming this week. 

I was not able to reproduce the whitespace issue, even with unsafe rendering. I wonder if it is in fact being returned from the query?

**Closed by chrisclark** 2024-01-31 14:23 UTC
